/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrialsRouteImport } from './routes/trials'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TrialsRoute = TrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/trials': typeof TrialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/trials': typeof TrialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRoute
  '/trials': typeof TrialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/pantry' | '/recipes' | '/trials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/pantry' | '/recipes' | '/trials'
  id: '__root__' | '/' | '/auth' | '/pantry' | '/recipes' | '/trials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PantryRoute: typeof PantryRoute
  RecipesRoute: typeof RecipesRoute
  TrialsRoute: typeof TrialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trials': {
      id: '/trials'
      path: '/trials'
      fullPath: '/trials'
      preLoaderRoute: typeof TrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PantryRoute: PantryRoute,
  RecipesRoute: RecipesRoute,
  TrialsRoute: TrialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
